# SysAdminProjects configuration
name: Aidan Pohl's Sysadmin Projects
description: The documentation for the projects I did in CYB-3353
url: "https://aidanpohl.github.io/SysAdminProjects"
markdown: GFM
